//context
import Provider from './components/Provider'
//styles
import './globals.css'
//components
import Header from './components/Header'
import Footer from './components/Footer'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Provider>
          <Header/>
          <main className=''>{children}</main>
          <Footer/>
        </Provider>
      </body>
    </html>
  )
}
